### ISSUE TITLE
Update tr.wikipedia-on-ipfs.org

### ISSUE THREAD

**Issue by lidel** [ipfs/distributed-wikipedia-mirror#60]
- [x] create new (test) snapshot 
  - couldn't extract fully, some files fail with  `other os error` (https://github.com/dignifiedquire/zim/issues/3)
  - fixed in `extract_zim` v0.2.0
- [x] ensure canonical link is correct (https://github.com/ipfs/distributed-wikipedia-mirror/issues/48#issuecomment-527230858 + https://github.com/ipfs/distributed-wikipedia-mirror/issues/65)
	- present in `wikipedia_tr_all_maxi_2019-10.zim`
- [x] ensure footer is updated (https://github.com/ipfs/distributed-wikipedia-mirror/issues/64
- [x] identify landing page parameter for `execute-changes.sh`
- [x] fix any broken JS by `execute-changes.sh`
- [x] recreate snapshot if needed
- [x] pin
  - [ ] set up collaborative pinning cluster (https://github.com/ipfs/distributed-wikipedia-mirror/issues/68)
- [x] update DNSLink at tr.wikipedia-on-ipfs.org

This could be done manually or as a part of #58

**Comment by lidel** [comment]
Couldn't extract fully, some files fail with  `other os error` described in https://github.com/dignifiedquire/zim/issues/3:

```console
> extract_zim --skip-link wikipedia_tr_all_maxi_2019-10.zim --out distributed-wikipedia-mirror/out2
Mon 28 Oct 12:26:11 CET 2019                                                                                                                       
Extracting file: wikipedia_tr_all_maxi_2019-10.zim to distributed-wikipedia-mirror/out2

  Creating map
  Extracting entries: 4808
  Spawning 4808 threads
couldn't create distributed-wikipedia-mirror/out2/A/Eternity: other os error
couldn't create distributed-wikipedia-mirror/out2/A/Eternity: other os error
couldn't create distributed-wikipedia-mirror/out2/A/Eternity: other os error
thread '<unnamed>' panicked at 'failed retry: couldn't create distributed-wikipedia-mirror/out2/A/Eternity: other os error', extract_zim.rs:133:17
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
couldn't create distributed-wikipedia-mirror/out2/A/Karacaoğlan: other os error
couldn't create distributed-wikipedia-mirror/out2/A/Karacaoğlan: other os error
couldn't create distributed-wikipedia-mirror/out2/A/Karacaoğlan: other os error
thread '<unnamed>' panicked at 'failed retry: couldn't create distributed-wikipedia-mirror/out2/A/Karacaoğlan: other os error', extract_zim.rs:133:17
couldn't create distributed-wikipedia-mirror/out2/A/Dört/Mazi_Kalbimde: other os error
couldn't create distributed-wikipedia-mirror/out2/A/Dört/Mazi_Kalbimde: other os error
couldn't create distributed-wikipedia-mirror/out2/A/Dört/Mazi_Kalbimde: other os error
thread '<unnamed>' panicked at 'failed retry: couldn't create distributed-wikipedia-mirror/out2/A/Dört/Mazi_Kalbimde: other os error', extract_zim.rs:133:17
couldn't create distributed-wikipedia-mirror/out2/A/HIV: other os error
couldn't create distributed-wikipedia-mirror/out2/A/HIV: other os error
couldn't create distributed-wikipedia-mirror/out2/A/HIV: other os error
thread '<unnamed>' panicked at 'failed retry: couldn't create distributed-wikipedia-mirror/out2/A/HIV: other os error', extract_zim.rs:133:17
couldn't create distributed-wikipedia-mirror/out2/A/Fredrikstad/Sarpsborg: other os error
couldn't create distributed-wikipedia-mirror/out2/A/Fredrikstad/Sarpsborg: other os error
couldn't create distributed-wikipedia-mirror/out2/A/Fredrikstad/Sarpsborg: other os error
thread '<unnamed>' panicked at 'failed retry: couldn't create distributed-wikipedia-mirror/out2/A/Fredrikstad/Sarpsborg: other os error', extract_zim.rs:133:17
...
```

**Comment by kelson42** [comment]
I want to make a side remark here. It is a pity that openZIM seems to not to provide an official tool you can just use to extract the ZIM content. I'm not sure about your exact requirement, but If I get them, I will seriously consider to do something to fix that problem for you. I want to really encourage you to create a feature request here https://github.com/openzim/zim-tools

**Comment by lidel** [comment]
@kelson42 thank you for bringing zim-tools to my attention! 
I was not around when tweaked [`extract_zim`](https://github.com/dignifiedquire/zim)  was created, but been told it was created either because `zimdump` was simply not around yet and original one was missing some features. 
I'll run some tests with `zimdump` and report back.

**Comment by dignifiedquire** [comment]
this error should be fixed now in the latest version of dignifiedquire/zim

**Comment by dignifiedquire** [comment]
Just ran the extraction, all fixed now

```sh
$time ./target/release/extract_zim --skip-link ~/Downloads/wikipedia_tr_all_maxi_2019-10.zim --out ./out
Extracting file: /Users/dignifiedquire/Downloads/wikipedia_tr_all_maxi_2019-10.zim to ./out

  Creating map
  Extracting entries: 4808
  Spawning 4808 tasks across 16 threads
  Extraction done in 47453ms
  Main page is Kullanıcı:The_other_Kiwix_guy/Landing
./target/release/extract_zim --skip-link  --out ./out  81.81s user 218.73s system 631% cpu 47.560 total
```

**Comment by lidel** [comment]
Thank you @dignifiedquire, this is great!

I took it for a spin and initial results are pretty good (wip in https://github.com/ipfs/distributed-wikipedia-mirror/pull/67):

- Unpacking `wikipedia_tr_all_maxi_2019-10.zim` took less than two minutes.
- Adding ~10GB to IPFS (0.5.0-dev with sharding+badgerds) in `--offline` mode took under 10 minutes.

Next step is to figure out #64 and landing page for `execute-changes.sh`

@kelson42 do you know why `.zim` file states that the Main page is [Kullanıcı:The_other_Kiwix_guy/Landing](https://tr.wikipedia.org/wiki/Kullan%C4%B1c%C4%B1:The_other_Kiwix_guy/Landing)? Is providing custom page a new convention in kiwix project?

**Comment by lidel** [comment]
- Original landing page at `./out/A/Anasayfa.html` seems to be truncated, the page includes only "article of the week" section, making it pretty bad landing page overall. 

- Tried to finish snapshot creation but scripts no longer work.
JS and the directory structure changed so much, that entire `execute-changes.sh` needs to be redone. 

- I also noticed `./out/-/j/js_modules/jsConfigVars.js` is invalid, its contents being: `(` (the single character). Not sure if its a bug in original ZIM, or problem with `extract_zim`.

**Comment by lidel** [comment]
#70 fixed the most painful blockers, and I was able to produce a new snapshot from [wikipedia_tr_all_maxi_2020-04.zim](https://download.kiwix.org/zim/wikipedia/wikipedia_tr_all_maxi_2020-04.zim):
* https://bafybeih3pdooy7tghdiuibphro6cwlyxp4henmmap7f2qm6fyitgpqafle.ipfs.dweb.link/

It has a pretty nice footer with useful information about mirror and its sources.

Two cosmetic issues remain: 
1. Main page at `/wiki/Anasayfa.html` is fetched for the date of unpacking ZIM, instead of  the day ZIM was created (This seems to be specific to Turkish wiki)
2. Some links on the Main page are broken, for example ones in header (`/wiki/Portal:Matematik.html` etc)
   - Not a problem, as the old version did not have links there anyway

Both can be fixed manually by patching HTML in `/wiki/Anasayfa.html`, but if anyone has time to fix them programmatically, that would be useful for other languages.

**Comment by momack2** [comment]
The view on mobile isn’t great - is that expected or a regression? 
![2E167E64-3635-4A38-8B5B-B6D3CD4DBB71](https://user-images.githubusercontent.com/618519/78949625-ef744b00-7a80-11ea-8d30-43ba6c3637d2.png)

**Comment by lidel** [comment]
@momack2  Yes, if we want "original" landing page this is something we need to fix manually (I believe the one in old snapshot was also crafted by hand).

Context: 

Original Main page is truncated or not included in many ZIM, so we have no "mobile friendly" version.
We download original HTML from wikipedia itself and add it to the unpacked ZIM snapshot, which as seen above requires some work.

FYI ZIM files often use a custom page provided by a contributor that makes more sense for offline use ([example](https://tr.wikipedia.org/wiki/Kullan%C4%B1c%C4%B1:The_other_Kiwix_guy/Landing)). You can see it does not have "topic of the day", instead its a dry list of wide topics ready to explore.

If we keep it, very little or no manual fixes may be needed because it is already simple enough to be mobile friendly – see this build where I left the original landing page from ZIM archive: https://bafybeieoya74422ovlmx23i5bxpuw2szsdrhsjwenfxkqoknw34jigcoua.ipfs.dweb.link/wiki/Anasayfa.html

**Comment by momack2** [comment]
Oh yeah - much better. Not perfect, but "good enough" for smooth browsing.

**Comment by lidel** [comment]
Ok friends, I've picked up the ball in #77  and produced a brand new snapshot from `wikipedia_tr_all_maxi_2021-02.zim`. If this goes well we will do the same for English (#61)

Highlights:
- fixed favicon
- native-looking footer
- source ZIM is added to the root directory and linked from the footer – this is extremely important for both auditability and kicks-off ZIM-on-IPFS efforts from #42  and  #71 
- article names no longer have `.html`, so paths look _exactly_ the same as on original Wikipedia :exploding_head: :sparkles: 
- we no longer overwrite original landing page from the day snapshot was taken:
   -  [`/wiki/`](https://dweb.link/ipfs/bafybeiexiynkovpcka22bmsbc4z4kvwtoggvyx7vzf5xfy5zo3vlpvyn2m/wiki/) uses "main page" from ZIM (date-agnostic, usually better suited for offline/exploratory use)
   - the original one is still available at [`/wiki/Anasayfa`](https://dweb.link/ipfs/bafybeiexiynkovpcka22bmsbc4z4kvwtoggvyx7vzf5xfy5zo3vlpvyn2m/wiki/Anasayfa) (matching https://tr.wikipedia.org/wiki/Anasayfa)


:point_right:  take it for a spin and comment if you find any issues:
- https://dweb.link/ipfs/bafybeiexiynkovpcka22bmsbc4z4kvwtoggvyx7vzf5xfy5zo3vlpvyn2m/ 
 (be mindful this is not pinned anywhere, only full copy is on my box for now, so ymmv)

**Comment by kelson42** [comment]
"Kiwix" in place of "kiwix" in the footer would be better.

**Comment by lidel** [comment]
@kelson42 added this in https://github.com/ipfs/distributed-wikipedia-mirror/pull/82 and created updated version:
* https://dweb.link/ipfs/bafybeieuutdavvf55sh3jktq2dpi2hkle6dtmebe7uklod3ramihyf3xa4

@mburns mind switching https://tr.dev.wikipedia-on-ipfs.org to the above CID?

**Comment by mburns** [comment]
done. :)

**Comment by lidel** [comment]
Ok, this should be good enough for now. 

DNSLink is updates and https://tr.wikipedia-on-ipfs.org now points at:
 `bafybeieuutdavvf55sh3jktq2dpi2hkle6dtmebe7uklod3ramihyf3xa4` (generated from `wikipedia_tr_all_maxi_2021-02`)

I'm now shifting focus to English one, tracking that in  #61

**Comment by VIP0000fa** [comment]
[Dino Game](https://dinogame.app/), a built-in Chrome offline game, features a pixelated T-Rex that players control. The goal is to jump over cacti and avoid obstacles as the game speeds up. Simple yet addictive, it provides a fun way to pass time while waiting for the internet to reconnect.  [](https://dinogame.app/)
