### ISSUE TITLE
Update en.wikipedia-on-ipfs.org

### ISSUE THREAD

**Issue by lidel** [ipfs/distributed-wikipedia-mirror#61]
- [x] set up domain name `en.wikipedia-on-ipfs.org` (https://github.com/ipfs/infra/issues/491)
- [x] [create new (test) snapshot](https://github.com/ipfs/distributed-wikipedia-mirror#how-to-add-new-wikipedia-snapshots-to-ipfs)
- [x] ensure canonical link is correct
  - this is blocked on upstream snapshots or updating our scripts: https://github.com/ipfs/distributed-wikipedia-mirror/issues/48#issuecomment-527230858  + https://github.com/ipfs/distributed-wikipedia-mirror/issues/65
- [x] ensure footer is updated (https://github.com/ipfs/distributed-wikipedia-mirror/issues/64)
- [ ] does search work / can work?
- [x] recreate snapshot if needed
- [ ] pin
  - [ ] set up collaborative pinning cluster (https://github.com/ipfs/distributed-wikipedia-mirror/issues/68)
- [ ] update DNSLink at en.wikipedia-on-ipfs.org (https://github.com/ipfs/infra/issues/491)

This could be done manually or as a part of #58

**Comment by RubenKelevra** [comment]
I would love to be part of the collaborative cluster, any ETA of that?

**Comment by lidel** [comment]
We should have collaborative cluster set up as soon as TR version is updated (track progress in #60 and #67). TR version is much smaller, so we use it as the test case. 

Due to other priorities and the size of EN version I can't commit to any specific date, but it should happen sometime in Q1 or Q2.

**Comment by RubenKelevra** [comment]
Cool news! Thanks for the work!

**Comment by RubenKelevra** [comment]
Cool news! Thanks for the work!

Maybe setup the cluster now, in the mean time people can join the cluster, while you work in an updated version of the data? :)

**Comment by lidel** [comment]
Let's track that in https://github.com/ipfs/distributed-wikipedia-mirror/issues/68

**Comment by ShadowJonathan** [comment]
Is it possible that this recreation job would be done on a monthly basis?

Every month a cron job would execute scaping/downloading + pushing it on IPFS, and then provide a new pin for the collaberative clusters, and update the dnslink to match the new version.

This also needs #71, if it's possible to de-duplicate unedited wiki pages between months, the new pin can stay up-to-date while requiring minimal extra data to be pulled.

**Comment by lidel** [comment]
Unfortunately English version is blocked on scraping/downloading step:

Upstream Kiwix project is having trouble with generating `.zim` archive which includes images, progress can be tracked in: https://github.com/openzim/mwoffliner/issues/1043

**Comment by ShadowJonathan** [comment]
Alright, i'll be keeping an eye out on that issue as well 👍

**Comment by lidel** [comment]
https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi_2020-06.zim.torrent just landed (88GB)

If anyone has bandwidth and storage to download it and make a test build using [instructions from `README`](https://github.com/ipfs/distributed-wikipedia-mirror/blob/master/README.md#how-to-add-new-wikipedia-snapshots-to-ipfs) to see if there are any issues and report back in comment here, that would help a lot. 

(I may do it eventually but super thin on free time so no ETA)

**Comment by OrionRafi3345** [comment]
The zim file has issue! its the corrupted one, probably corrupted during the zim generation!

**Comment by OrionRafi3345** [comment]
![Screenshot (22)](https://user-images.githubusercontent.com/47520335/86518150-d517f680-be50-11ea-9bef-3e55d62058c8.png)
![Screenshot (20)](https://user-images.githubusercontent.com/47520335/86518152-dc3f0480-be50-11ea-9310-dfb1399c5592.png)

See the difference! I already checked every valid working zim file. and try to compare it with "wikipedia_en_all_maxi_2020-06.zim" i notice every valid zim file contains some value after (61 69 6E)... But in "wikipedia_en_all_maxi_2020-06.zim" those values are only zeroes!  I downloaded it through torrent

**Comment by ShadowJonathan** [comment]
@lidel https://github.com/openzim/mwoffliner/issues/1043 seems to be fixed, would this issue be unblocked?

**Comment by kelson42** [comment]
@lidel Same remark here, was is still missing?

**Comment by lidel** [comment]
I dropped the ball here :( 
Main factor here was complexity of current solution vs the lack of time on my end, unfortunately.

I suspect by now we need to switch scripts from third-party ZIM decompressor [`extract_zim`](https://github.com/dignifiedquire/zim//)  to  official [`zimdump` from zim-tools](https://github.com/openzim/zim-tools) that has support for new compression scheme – https://github.com/ipfs/distributed-wikipedia-mirror/issues/66 

@kelson42 if you feel updating old Turkish and English snapshots is worth the effort, we could try to do a manual one-off update.  I'll try to allocate some time this week and see if its feasible with updated tooling.

But it is not sustainable long-term, for which we need to use ZIMs directly (https://github.com/ipfs/distributed-wikipedia-mirror/issues/42).

**Comment by lidel** [comment]
Now that #77 landed I will attempt to build English in the next two weeks and see how it goes.

**Comment by lidel** [comment]
`./mirrorzim.sh --languagecode=en --wikitype=wikipedia --hostingdnsdomain=en.wikipedia-on-ipfs.org` failed after ~21h with:

```
[..]
sed: couldn't open temporary file tmp/wikipedia_en_all_maxi_2020-12/wiki/sedNMHlNz: No space left on device
sed: couldn't open temporary file tmp/wikipedia_en_all_maxi_2020-12/wiki/sedhVhHaV: No space left on device
sed: couldn't open temporary file tmp/wikipedia_en_all_maxi_2020-12/wiki/sedWypHuG: No space left on device
sed: couldn't open temporary file tmp/wikipedia_en_all_maxi_2020-12/wiki/seda2aFbP: No space left on device
[..]
```

I suspected disk fs running out of inode, but thats not the case: 

```
Filesystem        Inodes    IUsed     IFree IUse% Mounted on
/dev/sda1      366215168 23700775 342514393    7% /media/test12tb
```

Just to remove sed as breaking point tweaked  indempotency  and disabled debug logs for redirect fix in https://github.com/ipfs/distributed-wikipedia-mirror/commit/84a70b9db1d8785de0dd0a6da046522a7855998c and restarted the build. :crossed_fingers:

**Comment by lidel** [comment]
Ok, it failed again after ~45h with the same error from sed :crying_cat_face: 
Good news is that my 1TB PCI-e SSD  arrived, I'll try to tweak fs parameters on it and resume.

**Comment by lidel** [comment]
The sed issue seems to be gone when running on SSD. 
I am now in process of `ipfs add` and it seems to be CPU-bound.
Will post updates when its done.

**Comment by lidel** [comment]
Badger seems to have a problem with many small files, filed separate https://github.com/ipfs/distributed-wikipedia-mirror/issues/85 to investigate.

Next:
- Will look into flatfs, maybe it is enough for this specific build.
- If not, will experiment with badger settings.

**Comment by lidel** [comment]
Good news! I ended up switching to flatfs datastore with `sync: false` and that finished without a hiccup:

- https://bafybeicarbywfeinwuwxcivurnle2mzwue42xr3c3dutrf2mngfun6pdum.ipfs.dweb.link/wiki/



Quick notes:

 -  This is a lot of files, so publishing them on DHT takes time. 
    - The first article of each category should work – I precached them on other node
    - If you are unable to load deeper articles via the public gateway, run own node and connect to mine via `ipfs swarm connect /p2p/12D3KooWFRcqpEhdCfAY6HYcrJaQjDBbPNp2ycxDY54LZNx6UgLM`
- We might be able to get the original `/wiki/Main_Page`  with fix from #83  or when we fix #80, but for now the kiwix one should do just fine. 
- :broken_heart:  `/wiki/Africa` seems to be broken due to #80, so far the only blocker I see for shipping this


@kelson42  any suggestion here for :broken_heart: ? 
Would your work related to "removing namespaces" help solving _exceptions, or is it unrelated? 

 I want to understand if it makes sense to add code for fixing exceptions as  post-unpack step, as it will be a very expensive process given the size of English wiki, or  if I should fill an issue in https://github.com/openzim/zim-tools/issues for this.

 FYSA the way we would  like to handle _exceptions like this is  is to move `wiki/Africa` (article) to `wiki/Africa/index.html` so it gets rendered correctly on IPFS gateway. This way folder does not collide with article, and you can have `wiki/Africa/Foo` or even `wiki/Africa/Foo/index.html`

**Comment by kelson42** [comment]
@lidel I have noe clue why th article "Africa dance" is an exception, so n way to say if this is legit or not.

**Comment by MatthewSteeples** [comment]
/ipfs/bafybeicarbywfeinwuwxcivurnle2mzwue42xr3c3dutrf2mngfun6pdum/wiki/Operating_system (linked to from /ipfs/bafybeicarbywfeinwuwxcivurnle2mzwue42xr3c3dutrf2mngfun6pdum/wiki/Software) does something weird too (might be the same issue as Africa Dance).

It shows the standard "folder" view with a single file in it called `kernel`, which just consists of a meta refresh tag that takes you to `Kernel_(operating_system)`, which doesn't exist

**Comment by ShadowJonathan** [comment]
Maybe `_`/` ` and uppercase-lowercase issues? Wikipedia corrects these automatically, but maybe this file doesn't?

**Comment by lidel** [comment]
I am sorry I was a bit vague in the problem description.  What I meant are issues with pages that have conflict with articles that had `/` in name, for example:
- [`/wiki/Africa`](https://bafybeicarbywfeinwuwxcivurnle2mzwue42xr3c3dutrf2mngfun6pdum.ipfs.dweb.link/wiki/Africa) and  [`/wiki/Dance`](https://bafybeicarbywfeinwuwxcivurnle2mzwue42xr3c3dutrf2mngfun6pdum.ipfs.dweb.link/wiki/Dance) are separate examples (I updated my original comment)
- [`/wiki/Asia`](https://bafybeicarbywfeinwuwxcivurnle2mzwue42xr3c3dutrf2mngfun6pdum.ipfs.dweb.link/wiki/Asia) is a good example, the second article produced a directory which blocked the first one:
  - https://en.wikipedia.org/wiki/Asia  
  - https://en.wikipedia.org/wiki/Asia/Tokyo (redirect)
- [`/wiki/Operating_system`](https://bafybeicarbywfeinwuwxcivurnle2mzwue42xr3c3dutrf2mngfun6pdum.ipfs.dweb.link/wiki/Operating_system) is the same type of conflict:
  - https://en.wikipedia.org/wiki/Operating_system
  - https://en.wikipedia.org/wiki/Operating_system/kernel (redirect)

**Comment by kelson42** [comment]
@lidel I think all of this is a problem we have identified 10 days ago around the mgmt of articles including a `/`. To me, this has to be treated/handled properly here. There is not much more which can be done IMO on `zimdump` side, other please let me know.

**Comment by lidel** [comment]
@kelson42 I've filled https://github.com/openzim/zim-tools/issues/226 with some ideas, let's discuss there if its feasible on your end.

**Comment by lidel** [comment]
Quick update on updating English to 2021-02:  I retried with fix for https://github.com/openzim/zim-tools/issues/227 and unpacking step went ok.  :+1: 
Unfortunately `flatfs` seem to take more space  than `badgerds` and I've run out of space on 1TB drive :man_facepalming: 
I'll see if I can work around this.

**Comment by lidel** [comment]
I cheated a bit and run `ipfs add --no-copy` with [filestore](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#ipfs-filestore) enabled overnight just to see how this alternative backend performs in hope it will "just work" – and it did!  Sadly I did not log times, but it seems to be faster than (flatfs with sync) and somewhere between (flatfs without sync) and (badger). For sure does not utilize full potential of SSD, but does the job as a slow workaround.

Anyway, generated a  version with changes from #88:
- virtually all `_exceptions` are fixed and can be loaded correctly
  - [`/wiki/Asia`](https://bafybeiehlicfvvqhauuxyj7ghspu63uv7vlq224aqytcfv5frewve5jxoq.ipfs.dweb.link/wiki/Asia) and [`/wiki/Asia/Tokyo`](https://bafybeiehlicfvvqhauuxyj7ghspu63uv7vlq224aqytcfv5frewve5jxoq.ipfs.dweb.link/wiki/Asia/Tokyo) (redirect) all work now, same with  [`/wiki/Operating_system`](https://bafybeiehlicfvvqhauuxyj7ghspu63uv7vlq224aqytcfv5frewve5jxoq.ipfs.dweb.link/wiki/Operating_system) and [`/wiki/Operating_system/kernel`](https://bafybeiehlicfvvqhauuxyj7ghspu63uv7vlq224aqytcfv5frewve5jxoq.ipfs.dweb.link/wiki/Operating_system/kernel)
- Main Page set in ZIM is used as landing page as-is (with minor fixes to paths and title)

Give it a try:

:point_right:  https://bafybeiehlicfvvqhauuxyj7ghspu63uv7vlq224aqytcfv5frewve5jxoq.ipfs.dweb.link/wiki/
This is not pinned anywhere yet. The first link of each category should work, but if you are unable to fetch deeper pages, manually connect to the provider via:
```
ipfs swarm connect /p2p/12D3KooWFRcqpEhdCfAY6HYcrJaQjDBbPNp2ycxDY54LZNx6UgLM
```

Lmk if you find any broken articles or unexpected behaviors. If nothing too severe, I'd like to ship this as-is, because its still way better than 4-year-old version at

**Comment by lidel** [comment]
FYI I'm taking `/p2p/12D3KooWFRcqpEhdCfAY6HYcrJaQjDBbPNp2ycxDY54LZNx6UgLM` offline for now to re-generate with fix from #89

**Comment by hf76yfu** [comment]
KUBET【KUBET88】được biết đến như nhà cái KU BET chuẩn hoặc Thiên Hạ Bet. cung cấp nhiều loại hình cá cược đa dạng và hấp dẫn để phục vụ nhu cầu của người chơi Thể Thao, Nhà cái này đã đi vào hoạt động từ rất lâu, tính đến nay đã 20 năm KUBET có tiền thân là một casino nổi tiếng tại Macao. Nhà cái đã được cấp giấy phép hoạt động hợp pháp của PAGCOR – Tập đoàn giải trí và Trò chơi Philippines. Đường link truy cập chính thức: https://kubet88.bio/

**Comment by hf76yfu** [comment]
[Kubet77](https://kubet77.support/)  là thương hiệu cá cược xanh chín hàng đầu tại châu Á. đơn vị đã chứng minh được chất lượng cũng như sức hấp dẫn của mình tại thị trường Việt Nam. Sau nhiều năm hoạt động, đơn vị đã trở thành nhà tài trợ độc quyền cho giải Primera La Liga của Tây Ban Nha. [](https://kubet77.support/)
